// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKsPJseaOVvbC7F9z_H6Ws8XPCZuzHWXo',
    appId: '1:719007502871:web:476b34f13a9f35d9ff8252',
    messagingSenderId: '719007502871',
    projectId: 'pruebalogin-c6d3d',
    authDomain: 'pruebalogin-c6d3d.firebaseapp.com',
    storageBucket: 'pruebalogin-c6d3d.appspot.com',
    measurementId: 'G-RNJC7Y466G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2CajDiH4xSq9at-E5fSctCjEpm5VblSQ',
    appId: '1:719007502871:android:103362ee396c027fff8252',
    messagingSenderId: '719007502871',
    projectId: 'pruebalogin-c6d3d',
    storageBucket: 'pruebalogin-c6d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsbqxncj-n8bTrVddt_BZYGLiMCvRoJY',
    appId: '1:719007502871:ios:8483a1d781211a94ff8252',
    messagingSenderId: '719007502871',
    projectId: 'pruebalogin-c6d3d',
    storageBucket: 'pruebalogin-c6d3d.appspot.com',
    androidClientId: '719007502871-f394dfi4gikl3mvdgqj1dpsfsabeihv7.apps.googleusercontent.com',
    iosClientId: '719007502871-qe384mnosj11kqapng3bs2b7ffprtvn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.seneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAsbqxncj-n8bTrVddt_BZYGLiMCvRoJY',
    appId: '1:719007502871:ios:8483a1d781211a94ff8252',
    messagingSenderId: '719007502871',
    projectId: 'pruebalogin-c6d3d',
    storageBucket: 'pruebalogin-c6d3d.appspot.com',
    androidClientId: '719007502871-f394dfi4gikl3mvdgqj1dpsfsabeihv7.apps.googleusercontent.com',
    iosClientId: '719007502871-qe384mnosj11kqapng3bs2b7ffprtvn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.seneca',
  );
}
